apiVersion: v1
kind: Service
metadata:
  labels:
    app: spark-submit
  name: spark-submit
spec:
  ports:
  - name: http
    port: 4040
    targetPort: 4040
  clusterIP: None
  selector:
    app: spark-submit
