apiVersion: v1
kind: PersistentVolume
metadata:
  name: host3-pv-had
spec:
  capacity:
    storage: 200Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  volumeMode: Filesystem
  storageClassName: hadoop
  local:
    path: /specify/your/own/path/ #specify your own path
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - host3 #change this to hostname
