apiVersion: v1
kind: PersistentVolume
metadata:
  name: host2-pv-ign
spec:
  capacity:
    storage: 100Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  volumeMode: Filesystem
  storageClassName: ignite
  local:
    path: /specify/your/own/path/ #specify your own path
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - host2 #change this to hostname
