apiVersion: v1
kind: Service
metadata:
  labels:
    app: spark
  name: spark
spec:
  clusterIP: None
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: master
    protocol: TCP
    port: 7077
    targetPort: 7077
  - name: rest
    protocol: TCP
    port: 6066
    targetPort: 6066
  selector:
    app: spark
