apiVersion: v1
kind: Service
metadata:
  labels:
    app: spark-worker
  name: spark-worker
spec:
  clusterIP: None
  ports:
  - name: http
    port: 8081
    targetPort: 8081
  selector:
    app: spark-worker
