version: '3.5'

services:
  cassandra-seed-node:
    image: cassandra:latest
    networks:
      - spark-net
    volumes:
      - /change/to/your/path:/var/lib/cassandra #change this to your path
    environment:
      - "CASSANDRA_SEEDS=tasks.cassandra-seed-node"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.cassandra-seednode == true

  cassandra-node:
    image: cassandra:latest
    networks:
      - spark-net
    volumes:
      - /change/to/your/path:/var/lib/cassandra #change this to your path
    environment:
      - "CASSANDRA_SEEDS=tasks.cassandra-seed-node"
    depends_on:
      - "cassandra-seed-node"
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.labels.cassandra == true

networks:
  spark-net:
    external: true

