version: '3.5'

# m+n node cluster
# If you see exit code 137 (OOM killer) then ensure Docker has access to more resources
services:
  ignite-master:
    image: apacheignite/ignite:2.5.0
    ports:
      - "47500:47500"
    networks:
      - spark-net
    volumes:
      - /change/to/your/path:/opt/ignite/apache-ignite-fabric/work/db #change to your own path
    environment:
      - "CONFIG_URI=http://neshpc4.fit.vutbr.cz:9999/example-persistent-store-master.xml"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.ignite == master
      labels:
        traefik.backend: ignite-master
        traefik.docker.network: spark-net
        traefik.port: 47500
        traefik.enable: "true"

  ignite-node:
    image: apacheignite/ignite:2.5.0
    ports:
      - "47501:47501"
    depends_on:
      - ignite-master
    networks:
      - spark-net
    volumes:
      - /change/to/your/path:/opt/ignite/apache-ignite-fabric/work/db #change to your own path
    environment:
      - "CONFIG_URI=http://neshpc4.fit.vutbr.cz:9999/example-persistent-store.xml"
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.labels.ignite == node
      labels:
        traefik.docker.network: spark-net
        traefik.port: 47501
        traefik.enable: "true"

networks:
  spark-net:
    external: true

