apiVersion: v1
kind: PersistentVolume
metadata:
  name: host2-pv-traefik
spec:
  capacity:
    storage: 100Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  volumeMode: Filesystem
  storageClassName: traefik
  local:
    path: /specify/your/own/path/ #specify your own path
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - host2 #change this to hostname
