apiVersion: v1
kind: Service
metadata:
  labels:
    app: ignite
  name: ignite
  namespace: default
spec:
  clusterIP: None
  ports:
  - name: "47500"
    port: 47500
    targetPort: 47500
  - name: "47501"
    port: 47501
    targetPort: 47501
  - name: "47502"
    port: 47502
    targetPort: 47502
  - name: rest
    port: 8080
    targetPort: 8080
  - name: sql
    port: 10800
    targetPort: 10800
  - name: thinclients
    port: 10900
    targetPort: 10900
  selector:
    app: ignite
