#---
#apiVersion: v1
#kind: Namespace
#metadata:
#  name: ignite

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ignite
  namespace: default
  labels:
    app: ignite

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: ignite
  namespace: default
  labels:
    app: ignite
rules:
- apiGroups: [""]
  resources: ["pods", "endpoints"]
  resourceNames: ["ignite"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: ignite
  namespace: default
  labels:
    app: ignite
roleRef:
  kind: ClusterRole #or ClusterRole
  name: ignite
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: ignite
  namespace: default

