apiVersion: v1
kind: PersistentVolume
metadata:
  name: host1-pv-nginx
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  volumeMode: Filesystem
  storageClassName: nginx
  local:
    path: /specify/your/own/path/ #specify your own path
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - host4 #change this to hostname
